// ============================================================
// AgentDyne MCP Server Registry
// As a founder in March 2026, MCP is the #1 differentiator.
// Every enterprise agent needs tool connections. This registry
// covers all major verified MCP servers across 12 categories.
// ============================================================

export interface MCPServer {
  id: string
  name: string
  description: string
  category: MCPCategory
  icon: string
  verified: boolean
  url?: string
  npmPackage?: string
  popularity: number
  tags: string[]
  capabilities: string[]
  setupMinutes: number
  pricingNote?: string
  docsUrl: string
  featured: boolean
  authType: "api_key" | "oauth" | "url" | "none"
  configExample: Record<string, string>
}

export type MCPCategory =
  | "databases"    | "communication"  | "productivity"
  | "development"  | "cloud"          | "ai"
  | "finance"      | "marketing"      | "security"
  | "files"        | "analytics"      | "ecommerce"

export const MCP_SERVERS: MCPServer[] = [
  // ── DATABASES ───────────────────────────────────────────────────────────
  {
    id: "supabase",
    name: "Supabase",
    description: "Full Postgres database access — query tables, run SQL, manage rows, realtime subscriptions, storage.",
    category: "databases", icon: "🗄️", verified: true,
    npmPackage: "@supabase/mcp-server",
    popularity: 5, featured: true, authType: "api_key",
    tags: ["postgres", "database", "realtime", "sql", "storage"],
    capabilities: ["read_data", "write_data", "run_sql", "manage_schema", "storage_ops", "realtime"],
    setupMinutes: 2,
    docsUrl: "https://supabase.com/docs/guides/getting-started/mcp",
    configExample: { SUPABASE_URL: "https://xxx.supabase.co", SUPABASE_SERVICE_ROLE_KEY: "eyJ..." },
  },
  {
    id: "postgres",
    name: "PostgreSQL",
    description: "Direct Postgres connection. Run arbitrary SQL, manage tables, inspect schemas, manage migrations.",
    category: "databases", icon: "🐘", verified: true,
    npmPackage: "@modelcontextprotocol/server-postgres",
    popularity: 5, featured: true, authType: "url",
    tags: ["postgres", "sql", "database"],
    capabilities: ["run_sql", "read_data", "write_data", "inspect_schema", "manage_tables"],
    setupMinutes: 3,
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/postgres",
    configExample: { POSTGRES_URL: "postgresql://user:pass@host:5432/db" },
  },
  {
    id: "mysql",
    name: "MySQL / MariaDB",
    description: "Connect to MySQL and MariaDB. Full query, schema inspection, and data management.",
    category: "databases", icon: "🐬", verified: true,
    npmPackage: "@modelcontextprotocol/server-mysql",
    popularity: 4, featured: false, authType: "url",
    tags: ["mysql", "mariadb", "sql", "database"],
    capabilities: ["run_sql", "read_data", "write_data", "inspect_schema"],
    setupMinutes: 3,
    docsUrl: "https://github.com/modelcontextprotocol/servers",
    configExample: { MYSQL_URL: "mysql://user:pass@host:3306/db" },
  },
  {
    id: "mongodb",
    name: "MongoDB",
    description: "Query and manage MongoDB collections, documents, and aggregation pipelines.",
    category: "databases", icon: "🍃", verified: true,
    npmPackage: "@modelcontextprotocol/server-mongodb",
    popularity: 4, featured: false, authType: "url",
    tags: ["mongodb", "nosql", "documents", "aggregation"],
    capabilities: ["find", "insert", "update", "delete", "aggregate", "create_index"],
    setupMinutes: 3,
    docsUrl: "https://github.com/modelcontextprotocol/servers",
    configExample: { MONGODB_URL: "mongodb+srv://user:pass@cluster.mongodb.net/db" },
  },
  {
    id: "redis",
    name: "Redis",
    description: "Get/set keys, manage lists, sorted sets, pub/sub, streams, and cache operations.",
    category: "databases", icon: "🔴", verified: true,
    npmPackage: "@modelcontextprotocol/server-redis",
    popularity: 4, featured: false, authType: "url",
    tags: ["redis", "cache", "pubsub", "queue", "streams"],
    capabilities: ["get", "set", "del", "list_ops", "sorted_sets", "pubsub", "streams"],
    setupMinutes: 2,
    docsUrl: "https://github.com/modelcontextprotocol/servers",
    configExample: { REDIS_URL: "redis://default:pass@host:6379" },
  },
  {
    id: "sqlite",
    name: "SQLite",
    description: "Local SQLite database. Perfect for lightweight agent data storage and prototyping.",
    category: "databases", icon: "💾", verified: true,
    npmPackage: "@modelcontextprotocol/server-sqlite",
    popularity: 3, featured: false, authType: "none",
    tags: ["sqlite", "sql", "local", "lightweight", "embedded"],
    capabilities: ["run_sql", "read_data", "write_data", "manage_tables"],
    setupMinutes: 1,
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/sqlite",
    configExample: { SQLITE_PATH: "/path/to/database.db" },
  },

  // ── COMMUNICATION ───────────────────────────────────────────────────────
  {
    id: "gmail",
    name: "Gmail",
    description: "Read, send, search, label, and manage Gmail messages, threads, and attachments.",
    category: "communication", icon: "📧", verified: true,
    url: "https://gmail.mcp.claude.com/mcp",
    popularity: 5, featured: true, authType: "oauth",
    tags: ["email", "gmail", "google", "inbox"],
    capabilities: ["read_emails", "send_email", "search_emails", "manage_labels", "manage_drafts", "read_attachments"],
    setupMinutes: 2,
    docsUrl: "https://docs.claude.ai/mcp/gmail",
    configExample: {},
  },
  {
    id: "slack",
    name: "Slack",
    description: "Post messages, read channels, manage workspaces, search messages, and handle reactions.",
    category: "communication", icon: "💬", verified: true,
    npmPackage: "@modelcontextprotocol/server-slack",
    popularity: 5, featured: true, authType: "api_key",
    tags: ["slack", "messaging", "team", "notifications", "channels"],
    capabilities: ["post_message", "read_channel", "list_channels", "search_messages", "manage_reactions", "get_thread"],
    setupMinutes: 5,
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/slack",
    configExample: { SLACK_BOT_TOKEN: "xoxb-...", SLACK_TEAM_ID: "T..." },
  },
  {
    id: "twilio",
    name: "Twilio",
    description: "Send SMS, WhatsApp messages, make voice calls, and check delivery status via Twilio.",
    category: "communication", icon: "📱", verified: true,
    npmPackage: "@modelcontextprotocol/server-twilio",
    popularity: 4, featured: false, authType: "api_key",
    tags: ["sms", "whatsapp", "voice", "twilio", "messaging"],
    capabilities: ["send_sms", "send_whatsapp", "make_call", "check_delivery", "manage_numbers"],
    setupMinutes: 5,
    docsUrl: "https://github.com/modelcontextprotocol/servers",
    configExample: { TWILIO_ACCOUNT_SID: "AC...", TWILIO_AUTH_TOKEN: "...", TWILIO_FROM: "+1..." },
  },
  {
    id: "discord",
    name: "Discord",
    description: "Send messages, manage channels, roles, and interact with Discord servers and bots.",
    category: "communication", icon: "🎮", verified: true,
    npmPackage: "@modelcontextprotocol/server-discord",
    popularity: 4, featured: false, authType: "api_key",
    tags: ["discord", "gaming", "community", "bot", "server"],
    capabilities: ["send_message", "manage_channels", "manage_roles", "get_members", "create_webhook"],
    setupMinutes: 5,
    docsUrl: "https://github.com/modelcontextprotocol/servers",
    configExample: { DISCORD_BOT_TOKEN: "MTI..." },
  },
  {
    id: "sendgrid",
    name: "SendGrid",
    description: "Send transactional emails, manage templates, lists, and track email analytics.",
    category: "communication", icon: "✉️", verified: true,
    npmPackage: "@modelcontextprotocol/server-sendgrid",
    popularity: 4, featured: false, authType: "api_key",
    tags: ["email", "sendgrid", "transactional", "marketing", "templates"],
    capabilities: ["send_email", "manage_templates", "manage_lists", "email_analytics"],
    setupMinutes: 3,
    docsUrl: "https://docs.sendgrid.com",
    configExample: { SENDGRID_API_KEY: "SG...." },
  },

  // ── PRODUCTIVITY ────────────────────────────────────────────────────────
  {
    id: "google-calendar",
    name: "Google Calendar",
    description: "Read, create, update calendar events, check availability, and manage schedules.",
    category: "productivity", icon: "📅", verified: true,
    url: "https://gcal.mcp.claude.com/mcp",
    popularity: 5, featured: true, authType: "oauth",
    tags: ["calendar", "scheduling", "google", "meetings", "events"],
    capabilities: ["read_events", "create_event", "update_event", "delete_event", "check_availability", "manage_calendars"],
    setupMinutes: 2,
    docsUrl: "https://docs.claude.ai/mcp/google-calendar",
    configExample: {},
  },
  {
    id: "notion",
    name: "Notion",
    description: "Read and write Notion pages, query databases, create blocks. The ultimate knowledge base integration.",
    category: "productivity", icon: "📝", verified: true,
    npmPackage: "@modelcontextprotocol/server-notion",
    popularity: 5, featured: true, authType: "api_key",
    tags: ["notion", "notes", "wiki", "database", "documents", "knowledge"],
    capabilities: ["read_page", "write_page", "query_database", "create_block", "search", "create_page"],
    setupMinutes: 5,
    docsUrl: "https://developers.notion.com",
    configExample: { NOTION_API_KEY: "secret_..." },
  },
  {
    id: "google-drive",
    name: "Google Drive",
    description: "Read, write, search, share, and manage files across Google Drive including Docs, Sheets, Slides.",
    category: "productivity", icon: "📁", verified: true,
    url: "https://drive.mcp.claude.com/mcp",
    popularity: 5, featured: true, authType: "oauth",
    tags: ["google", "drive", "files", "docs", "sheets", "slides"],
    capabilities: ["list_files", "read_file", "write_file", "search_files", "share_file", "create_folder"],
    setupMinutes: 2,
    docsUrl: "https://docs.claude.ai/mcp/google-drive",
    configExample: {},
  },
  {
    id: "linear",
    name: "Linear",
    description: "Manage issues, projects, cycles, and sprints in Linear. Built for modern engineering teams.",
    category: "productivity", icon: "📊", verified: true,
    npmPackage: "@modelcontextprotocol/server-linear",
    popularity: 4, featured: false, authType: "api_key",
    tags: ["linear", "issues", "projects", "engineering", "agile", "sprints"],
    capabilities: ["create_issue", "update_issue", "list_issues", "manage_projects", "manage_cycles"],
    setupMinutes: 5,
    docsUrl: "https://developers.linear.app",
    configExample: { LINEAR_API_KEY: "lin_api_..." },
  },
  {
    id: "asana",
    name: "Asana",
    description: "Create, update, and manage Asana tasks, projects, teams, and portfolios.",
    category: "productivity", icon: "✅", verified: true,
    url: "https://mcp.asana.com/sse",
    popularity: 4, featured: false, authType: "oauth",
    tags: ["asana", "tasks", "projects", "team", "portfolio"],
    capabilities: ["create_task", "update_task", "list_tasks", "manage_projects", "manage_portfolios"],
    setupMinutes: 3,
    docsUrl: "https://developers.asana.com/docs/mcp",
    configExample: {},
  },
  {
    id: "jira",
    name: "Jira",
    description: "Full Jira integration — create issues, update tickets, manage sprints, boards, and backlogs.",
    category: "productivity", icon: "🎯", verified: true,
    npmPackage: "@modelcontextprotocol/server-jira",
    popularity: 4, featured: false, authType: "api_key",
    tags: ["jira", "tickets", "sprints", "agile", "atlassian", "backlog"],
    capabilities: ["create_issue", "update_issue", "search_jql", "manage_sprints", "manage_boards"],
    setupMinutes: 5,
    docsUrl: "https://developer.atlassian.com/cloud/jira",
    configExample: { JIRA_URL: "https://yourorg.atlassian.net", JIRA_EMAIL: "you@org.com", JIRA_API_TOKEN: "..." },
  },
  {
    id: "airtable",
    name: "Airtable",
    description: "Read and write Airtable bases, tables, and records. Powerful no-code database integration.",
    category: "productivity", icon: "🗂️", verified: true,
    npmPackage: "@modelcontextprotocol/server-airtable",
    popularity: 4, featured: false, authType: "api_key",
    tags: ["airtable", "spreadsheet", "database", "no-code", "records"],
    capabilities: ["list_records", "create_record", "update_record", "delete_record", "search_records"],
    setupMinutes: 3,
    docsUrl: "https://airtable.com/developers/web/api",
    configExample: { AIRTABLE_API_KEY: "pat...", AIRTABLE_BASE_ID: "app..." },
  },

  // ── DEVELOPMENT ─────────────────────────────────────────────────────────
  {
    id: "github",
    name: "GitHub",
    description: "Read repos, create PRs, manage issues and reviews, run workflows, search code across GitHub.",
    category: "development", icon: "🐙", verified: true,
    npmPackage: "@modelcontextprotocol/server-github",
    popularity: 5, featured: true, authType: "api_key",
    tags: ["github", "git", "code", "repos", "prs", "actions"],
    capabilities: ["read_repo", "create_pr", "manage_issues", "run_workflow", "search_code", "manage_reviews"],
    setupMinutes: 3,
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/github",
    configExample: { GITHUB_TOKEN: "ghp_..." },
  },
  {
    id: "filesystem",
    name: "Filesystem",
    description: "Read, write, list, copy, move, and manage local files and directories securely.",
    category: "files", icon: "📂", verified: true,
    npmPackage: "@modelcontextprotocol/server-filesystem",
    popularity: 5, featured: true, authType: "none",
    tags: ["files", "filesystem", "local", "storage", "directories"],
    capabilities: ["read_file", "write_file", "list_directory", "create_directory", "delete_file", "move_file"],
    setupMinutes: 1,
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
    configExample: { ALLOWED_DIRS: "/home/user/data,/tmp/workspace" },
  },
  {
    id: "browserbase",
    name: "Browserbase",
    description: "Cloud browser automation — navigate pages, click, fill forms, extract data, take screenshots.",
    category: "development", icon: "🌐", verified: true,
    npmPackage: "@browserbasehq/mcp-browserbase",
    popularity: 4, featured: true, authType: "api_key",
    tags: ["browser", "automation", "scraping", "web", "testing"],
    capabilities: ["navigate", "click", "fill_form", "screenshot", "extract_data", "execute_js"],
    setupMinutes: 5,
    docsUrl: "https://docs.browserbase.com/mcp",
    configExample: { BROWSERBASE_API_KEY: "bb_...", BROWSERBASE_PROJECT_ID: "..." },
  },
  {
    id: "puppeteer",
    name: "Puppeteer",
    description: "Headless Chrome automation for web scraping, PDF generation, and end-to-end testing.",
    category: "development", icon: "🎭", verified: true,
    npmPackage: "@modelcontextprotocol/server-puppeteer",
    popularity: 4, featured: false, authType: "none",
    tags: ["puppeteer", "browser", "scraping", "headless", "pdf", "testing"],
    capabilities: ["navigate", "screenshot", "pdf", "click", "fill_form", "scrape"],
    setupMinutes: 5,
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/puppeteer",
    configExample: {},
  },
  {
    id: "gitlab",
    name: "GitLab",
    description: "Manage GitLab repos, merge requests, pipelines, issues, and CI/CD jobs.",
    category: "development", icon: "🦊", verified: true,
    npmPackage: "@modelcontextprotocol/server-gitlab",
    popularity: 3, featured: false, authType: "api_key",
    tags: ["gitlab", "git", "cicd", "merge-requests", "pipelines"],
    capabilities: ["read_repo", "create_mr", "manage_issues", "trigger_pipeline", "manage_variables"],
    setupMinutes: 5,
    docsUrl: "https://docs.gitlab.com/ee/api",
    configExample: { GITLAB_URL: "https://gitlab.com", GITLAB_TOKEN: "glpat-..." },
  },

  // ── CLOUD ───────────────────────────────────────────────────────────────
  {
    id: "aws",
    name: "AWS",
    description: "Full AWS SDK — S3, Lambda, DynamoDB, EC2, SQS, SNS, CloudWatch, IAM and more.",
    category: "cloud", icon: "☁️", verified: true,
    npmPackage: "@modelcontextprotocol/server-aws",
    popularity: 5, featured: true, authType: "api_key",
    tags: ["aws", "s3", "lambda", "cloud", "amazon", "ec2", "dynamodb"],
    capabilities: ["s3_operations", "invoke_lambda", "dynamodb_ops", "manage_ec2", "sqs_ops", "cloudwatch"],
    setupMinutes: 10,
    docsUrl: "https://github.com/modelcontextprotocol/servers",
    configExample: { AWS_ACCESS_KEY_ID: "AKIA...", AWS_SECRET_ACCESS_KEY: "...", AWS_REGION: "us-east-1" },
  },
  {
    id: "gcp",
    name: "Google Cloud",
    description: "BigQuery, Cloud Storage, Cloud Functions, Pub/Sub, Spanner and more GCP services.",
    category: "cloud", icon: "🌤️", verified: true,
    npmPackage: "@modelcontextprotocol/server-gcp",
    popularity: 4, featured: false, authType: "api_key",
    tags: ["gcp", "bigquery", "gcs", "google-cloud", "pubsub"],
    capabilities: ["bigquery_query", "gcs_operations", "pubsub", "cloud_functions", "spanner"],
    setupMinutes: 10,
    docsUrl: "https://cloud.google.com/docs",
    configExample: { GOOGLE_APPLICATION_CREDENTIALS: "/path/to/service-account.json", GCP_PROJECT_ID: "..." },
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    description: "Deploy Workers, manage KV, D1, R2, Queues, DNS zones, and Cache from your agents.",
    category: "cloud", icon: "🔶", verified: true,
    npmPackage: "@cloudflare/mcp-server-cloudflare",
    popularity: 4, featured: false, authType: "api_key",
    tags: ["cloudflare", "workers", "kv", "edge", "dns", "d1", "r2"],
    capabilities: ["deploy_worker", "kv_ops", "d1_query", "r2_ops", "manage_dns", "purge_cache"],
    setupMinutes: 5,
    docsUrl: "https://developers.cloudflare.com/mcp",
    configExample: { CLOUDFLARE_API_TOKEN: "...", CLOUDFLARE_ACCOUNT_ID: "..." },
  },
  {
    id: "vercel",
    name: "Vercel",
    description: "Deploy projects, manage domains, environment variables, and check deployment status.",
    category: "cloud", icon: "▲", verified: true,
    npmPackage: "@modelcontextprotocol/server-vercel",
    popularity: 4, featured: false, authType: "api_key",
    tags: ["vercel", "deploy", "serverless", "nextjs", "edge"],
    capabilities: ["deploy_project", "manage_domains", "manage_env_vars", "get_logs", "check_deployments"],
    setupMinutes: 3,
    docsUrl: "https://vercel.com/docs/rest-api",
    configExample: { VERCEL_TOKEN: "...", VERCEL_TEAM_ID: "team_..." },
  },

  // ── AI ──────────────────────────────────────────────────────────────────
  {
    id: "anthropic",
    name: "Anthropic Claude",
    description: "Call Claude models directly — completions, vision, tool use, and batch processing with full control.",
    category: "ai", icon: "🤖", verified: true,
    popularity: 5, featured: true, authType: "api_key",
    tags: ["claude", "anthropic", "llm", "ai", "vision", "tool-use"],
    capabilities: ["completions", "vision", "tool_use", "batch", "streaming"],
    setupMinutes: 2,
    docsUrl: "https://docs.anthropic.com",
    configExample: { ANTHROPIC_API_KEY: "sk-ant-..." },
  },
  {
    id: "openai",
    name: "OpenAI",
    description: "GPT-4o, DALL-E 3, Whisper, Embeddings, Assistants API — the full OpenAI platform.",
    category: "ai", icon: "⚡", verified: true,
    npmPackage: "@modelcontextprotocol/server-openai",
    popularity: 5, featured: true, authType: "api_key",
    tags: ["openai", "gpt", "dalle", "whisper", "embeddings", "assistants"],
    capabilities: ["chat", "images", "speech_to_text", "embeddings", "assistants", "streaming"],
    setupMinutes: 2,
    docsUrl: "https://platform.openai.com/docs",
    configExample: { OPENAI_API_KEY: "sk-..." },
  },
  {
    id: "pinecone",
    name: "Pinecone",
    description: "Vector database for RAG — upsert, query, and manage embeddings at production scale.",
    category: "ai", icon: "🌲", verified: true,
    npmPackage: "@modelcontextprotocol/server-pinecone",
    popularity: 4, featured: false, authType: "api_key",
    tags: ["pinecone", "vectors", "embeddings", "rag", "semantic-search"],
    capabilities: ["upsert_vectors", "query", "delete", "list_indexes", "create_index"],
    setupMinutes: 5,
    docsUrl: "https://docs.pinecone.io",
    configExample: { PINECONE_API_KEY: "...", PINECONE_ENVIRONMENT: "gcp-starter" },
  },
  {
    id: "qdrant",
    name: "Qdrant",
    description: "Open-source vector search engine. Store and search high-dimensional vectors for AI applications.",
    category: "ai", icon: "🔮", verified: true,
    npmPackage: "@modelcontextprotocol/server-qdrant",
    popularity: 3, featured: false, authType: "api_key",
    tags: ["qdrant", "vectors", "search", "embeddings", "self-hosted"],
    capabilities: ["upsert_vectors", "search", "delete", "manage_collections"],
    setupMinutes: 5,
    docsUrl: "https://qdrant.tech/documentation",
    configExample: { QDRANT_URL: "https://xxx.qdrant.io", QDRANT_API_KEY: "..." },
  },

  // ── FINANCE ─────────────────────────────────────────────────────────────
  {
    id: "stripe",
    name: "Stripe",
    description: "Create charges, manage customers, subscriptions, refunds, invoices, and Connect accounts.",
    category: "finance", icon: "💳", verified: true,
    npmPackage: "@modelcontextprotocol/server-stripe",
    popularity: 5, featured: true, authType: "api_key",
    tags: ["stripe", "payments", "subscriptions", "billing", "invoices"],
    capabilities: ["create_charge", "manage_customers", "create_subscription", "refund", "create_invoice", "manage_connect"],
    setupMinutes: 5,
    docsUrl: "https://stripe.com/docs",
    configExample: { STRIPE_SECRET_KEY: "sk_live_..." },
  },
  {
    id: "plaid",
    name: "Plaid",
    description: "Connect to bank accounts, retrieve transactions, balances, and financial data via Plaid.",
    category: "finance", icon: "🏦", verified: true,
    npmPackage: "@modelcontextprotocol/server-plaid",
    popularity: 4, featured: false, authType: "api_key",
    tags: ["plaid", "banking", "transactions", "fintech", "open-banking"],
    capabilities: ["get_transactions", "get_balance", "get_accounts", "verify_identity"],
    setupMinutes: 10,
    docsUrl: "https://plaid.com/docs",
    configExample: { PLAID_CLIENT_ID: "...", PLAID_SECRET: "...", PLAID_ENV: "production" },
  },
  {
    id: "quickbooks",
    name: "QuickBooks",
    description: "Read invoices, expenses, P&L, balance sheets, and manage accounting data.",
    category: "finance", icon: "📒", verified: true,
    popularity: 3, featured: false, authType: "oauth",
    tags: ["quickbooks", "accounting", "invoices", "finance", "intuit"],
    capabilities: ["read_invoices", "read_expenses", "financial_reports", "create_invoice", "manage_vendors"],
    setupMinutes: 10,
    docsUrl: "https://developer.intuit.com",
    configExample: {},
  },

  // ── MARKETING & CRM ─────────────────────────────────────────────────────
  {
    id: "hubspot",
    name: "HubSpot",
    description: "Full CRM — contacts, deals, companies, emails, pipelines, and marketing automation.",
    category: "marketing", icon: "🧡", verified: true,
    npmPackage: "@modelcontextprotocol/server-hubspot",
    popularity: 4, featured: false, authType: "api_key",
    tags: ["hubspot", "crm", "marketing", "contacts", "deals", "pipeline"],
    capabilities: ["manage_contacts", "manage_deals", "manage_companies", "email_campaigns", "analytics"],
    setupMinutes: 5,
    docsUrl: "https://developers.hubspot.com",
    configExample: { HUBSPOT_ACCESS_TOKEN: "pat-..." },
  },
  {
    id: "salesforce",
    name: "Salesforce",
    description: "SOQL queries, Apex execution, manage leads, opportunities, accounts, and reports.",
    category: "marketing", icon: "☁️", verified: true,
    popularity: 4, featured: false, authType: "oauth",
    tags: ["salesforce", "crm", "leads", "opportunities", "soql", "apex"],
    capabilities: ["soql_query", "manage_leads", "manage_opportunities", "manage_accounts", "run_reports"],
    setupMinutes: 10,
    docsUrl: "https://developer.salesforce.com",
    configExample: {},
  },
  {
    id: "mailchimp",
    name: "Mailchimp",
    description: "Manage email campaigns, lists, automations, and audience segments in Mailchimp.",
    category: "marketing", icon: "🐒", verified: true,
    npmPackage: "@modelcontextprotocol/server-mailchimp",
    popularity: 3, featured: false, authType: "api_key",
    tags: ["mailchimp", "email", "campaigns", "marketing", "newsletters"],
    capabilities: ["manage_campaigns", "manage_lists", "send_campaign", "analytics", "manage_segments"],
    setupMinutes: 5,
    docsUrl: "https://mailchimp.com/developer",
    configExample: { MAILCHIMP_API_KEY: "...-us1", MAILCHIMP_SERVER: "us1" },
  },

  // ── SECURITY ────────────────────────────────────────────────────────────
  {
    id: "1password",
    name: "1Password",
    description: "Securely retrieve credentials, secrets, and notes from 1Password vaults.",
    category: "security", icon: "🔐", verified: true,
    npmPackage: "@1password/mcp-server",
    popularity: 4, featured: false, authType: "api_key",
    tags: ["1password", "secrets", "credentials", "vault", "passwords"],
    capabilities: ["get_secret", "list_vaults", "search_items", "create_item"],
    setupMinutes: 5,
    docsUrl: "https://developer.1password.com/docs/mcp",
    configExample: { OP_SERVICE_ACCOUNT_TOKEN: "ops_..." },
  },
  {
    id: "hashicorp-vault",
    name: "HashiCorp Vault",
    description: "Retrieve secrets, dynamic credentials, and manage policies from Vault.",
    category: "security", icon: "🔒", verified: true,
    npmPackage: "@modelcontextprotocol/server-vault",
    popularity: 3, featured: false, authType: "api_key",
    tags: ["vault", "hashicorp", "secrets", "credentials", "pki"],
    capabilities: ["read_secret", "write_secret", "list_secrets", "get_dynamic_creds"],
    setupMinutes: 10,
    docsUrl: "https://developer.hashicorp.com/vault/docs",
    configExample: { VAULT_ADDR: "https://vault.example.com", VAULT_TOKEN: "hvs...." },
  },

  // ── ANALYTICS ───────────────────────────────────────────────────────────
  {
    id: "posthog",
    name: "PostHog",
    description: "Query events, run cohort analysis, manage feature flags, A/B tests and session replays.",
    category: "analytics", icon: "🦔", verified: true,
    popularity: 4, featured: false, authType: "api_key",
    tags: ["posthog", "analytics", "events", "feature-flags", "ab-testing"],
    capabilities: ["query_events", "manage_flags", "cohort_analysis", "funnel_analysis", "session_replay"],
    setupMinutes: 5,
    docsUrl: "https://posthog.com/docs/libraries/mcp",
    configExample: { POSTHOG_API_KEY: "phc_...", POSTHOG_HOST: "https://app.posthog.com" },
  },
  {
    id: "google-analytics",
    name: "Google Analytics",
    description: "Pull GA4 metrics — sessions, conversions, user journeys, real-time data, and custom reports.",
    category: "analytics", icon: "📈", verified: true,
    popularity: 4, featured: false, authType: "oauth",
    tags: ["google-analytics", "ga4", "analytics", "traffic", "conversions"],
    capabilities: ["run_report", "realtime_data", "audience_data", "conversion_tracking", "custom_dimensions"],
    setupMinutes: 10,
    docsUrl: "https://developers.google.com/analytics",
    configExample: {},
  },
  {
    id: "mixpanel",
    name: "Mixpanel",
    description: "Query Mixpanel events, run funnel and retention analyses, manage cohorts.",
    category: "analytics", icon: "🎯", verified: true,
    popularity: 3, featured: false, authType: "api_key",
    tags: ["mixpanel", "analytics", "funnels", "retention", "events"],
    capabilities: ["query_events", "funnel_analysis", "retention_analysis", "manage_cohorts"],
    setupMinutes: 5,
    docsUrl: "https://developer.mixpanel.com",
    configExample: { MIXPANEL_SERVICE_ACCOUNT_USERNAME: "...", MIXPANEL_SERVICE_ACCOUNT_SECRET: "...", MIXPANEL_PROJECT_ID: "..." },
  },

  // ── E-COMMERCE ──────────────────────────────────────────────────────────
  {
    id: "shopify",
    name: "Shopify",
    description: "Full Shopify Admin — manage products, orders, customers, inventory, discounts, and analytics.",
    category: "ecommerce", icon: "🛍️", verified: true,
    npmPackage: "@modelcontextprotocol/server-shopify",
    popularity: 4, featured: false, authType: "api_key",
    tags: ["shopify", "ecommerce", "orders", "products", "inventory", "customers"],
    capabilities: ["manage_products", "manage_orders", "manage_customers", "inventory_ops", "discount_ops"],
    setupMinutes: 5,
    docsUrl: "https://shopify.dev/docs/apps/tools/mcp",
    configExample: { SHOPIFY_STORE_URL: "your-store.myshopify.com", SHOPIFY_ACCESS_TOKEN: "shpat_..." },
  },
  {
    id: "woocommerce",
    name: "WooCommerce",
    description: "Manage WooCommerce products, orders, customers, and store settings via REST API.",
    category: "ecommerce", icon: "🛒", verified: true,
    popularity: 3, featured: false, authType: "api_key",
    tags: ["woocommerce", "wordpress", "ecommerce", "orders", "products"],
    capabilities: ["manage_products", "manage_orders", "manage_customers", "store_settings"],
    setupMinutes: 5,
    docsUrl: "https://woocommerce.github.io/woocommerce-rest-api-docs",
    configExample: { WC_URL: "https://yourstore.com", WC_CONSUMER_KEY: "ck_...", WC_CONSUMER_SECRET: "cs_..." },
  },
]

// ── CATEGORY METADATA ────────────────────────────────────────────────────────
export const MCP_CATEGORIES: { id: MCPCategory; label: string; icon: string; count: number }[] = [
  { id: "databases",     label: "Databases",      icon: "🗄️", count: MCP_SERVERS.filter(s => s.category === "databases").length },
  { id: "communication", label: "Communication",   icon: "💬", count: MCP_SERVERS.filter(s => s.category === "communication").length },
  { id: "productivity",  label: "Productivity",    icon: "⚡", count: MCP_SERVERS.filter(s => s.category === "productivity").length },
  { id: "development",   label: "Development",     icon: "💻", count: MCP_SERVERS.filter(s => s.category === "development").length },
  { id: "cloud",         label: "Cloud",           icon: "☁️", count: MCP_SERVERS.filter(s => s.category === "cloud").length },
  { id: "ai",            label: "AI & ML",         icon: "🤖", count: MCP_SERVERS.filter(s => s.category === "ai").length },
  { id: "finance",       label: "Finance",         icon: "💰", count: MCP_SERVERS.filter(s => s.category === "finance").length },
  { id: "marketing",     label: "Marketing & CRM", icon: "📣", count: MCP_SERVERS.filter(s => s.category === "marketing").length },
  { id: "security",      label: "Security",        icon: "🔐", count: MCP_SERVERS.filter(s => s.category === "security").length },
  { id: "files",         label: "Files & Storage", icon: "📂", count: MCP_SERVERS.filter(s => s.category === "files").length },
  { id: "analytics",     label: "Analytics",       icon: "📊", count: MCP_SERVERS.filter(s => s.category === "analytics").length },
  { id: "ecommerce",     label: "E-Commerce",      icon: "🛍️", count: MCP_SERVERS.filter(s => s.category === "ecommerce").length },
]

export const FEATURED_MCP = MCP_SERVERS.filter(s => s.featured)
export const getMCPById = (id: string) => MCP_SERVERS.find(s => s.id === id)
export const getMCPByCategory = (cat: MCPCategory) => MCP_SERVERS.filter(s => s.category === cat)
