// Auto-generated by: npm run db:generate
// Run this command after setting up your Supabase project to regenerate

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          username: string | null
          avatar_url: string | null
          bio: string | null
          website: string | null
          company: string | null
          role: "user" | "seller" | "admin"
          is_verified: boolean
          is_banned: boolean
          stripe_customer_id: string | null
          stripe_connect_account_id: string | null
          stripe_connect_onboarded: boolean
          subscription_plan: "free" | "starter" | "pro" | "enterprise"
          subscription_status: "active" | "past_due" | "canceled" | "trialing" | null
          subscription_id: string | null
          monthly_execution_quota: number
          executions_used_this_month: number
          quota_reset_date: string
          total_earned: number
          total_spent: number
          created_at: string
          updated_at: string
        }
        Insert: Partial<Database["public"]["Tables"]["profiles"]["Row"]> & { id: string; email: string }
        Update: Partial<Database["public"]["Tables"]["profiles"]["Row"]>
      }
      agents: {
        Row: {
          id: string
          seller_id: string
          name: string
          slug: string
          description: string
          long_description: string | null
          category: string
          tags: string[]
          status: "draft" | "pending_review" | "active" | "suspended" | "archived"
          is_featured: boolean
          is_verified: boolean
          pricing_model: "free" | "per_call" | "subscription" | "freemium"
          price_per_call: number
          subscription_price_monthly: number
          subscription_price_yearly: number
          free_calls_per_month: number
          model_provider: string
          model_name: string
          system_prompt: string | null
          tools: Json
          mcp_servers: Json
          max_tokens: number
          temperature: number
          timeout_seconds: number
          input_schema: Json
          output_schema: Json
          example_inputs: Json
          icon_url: string | null
          cover_url: string | null
          demo_video_url: string | null
          total_executions: number
          successful_executions: number
          average_latency_ms: number
          average_rating: number
          total_reviews: number
          total_revenue: number
          monthly_executions: number
          meta_title: string | null
          meta_description: string | null
          version: string
          changelog: Json
          documentation: string | null
          created_at: string
          updated_at: string
        }
        Insert: Partial<Database["public"]["Tables"]["agents"]["Row"]> & { seller_id: string; name: string; slug: string; description: string; category: string }
        Update: Partial<Database["public"]["Tables"]["agents"]["Row"]>
      }
      api_keys: {
        Row: {
          id: string
          user_id: string
          name: string
          key_hash: string
          key_prefix: string
          last_used_at: string | null
          expires_at: string | null
          is_active: boolean
          permissions: string[]
          rate_limit_per_minute: number
          total_calls: number
          created_at: string
        }
        Insert: Partial<Database["public"]["Tables"]["api_keys"]["Row"]> & { user_id: string; name: string; key_hash: string; key_prefix: string }
        Update: Partial<Database["public"]["Tables"]["api_keys"]["Row"]>
      }
      executions: {
        Row: {
          id: string
          agent_id: string | null
          user_id: string | null
          api_key_id: string | null
          status: "queued" | "running" | "success" | "failed" | "timeout"
          input: Json
          output: Json | null
          error_message: string | null
          tokens_input: number
          tokens_output: number
          latency_ms: number | null
          cost_usd: number
          is_billed: boolean
          billed_at: string | null
          created_at: string
          completed_at: string | null
        }
        Insert: Partial<Database["public"]["Tables"]["executions"]["Row"]> & { input: Json }
        Update: Partial<Database["public"]["Tables"]["executions"]["Row"]>
      }
      transactions: {
        Row: {
          id: string
          user_id: string | null
          agent_id: string | null
          seller_id: string | null
          stripe_payment_intent_id: string | null
          stripe_charge_id: string | null
          amount: number
          platform_fee: number
          seller_amount: number
          currency: string
          type: string
          status: string
          metadata: Json
          created_at: string
        }
        Insert: Partial<Database["public"]["Tables"]["transactions"]["Row"]> & { amount: number; type: string }
        Update: Partial<Database["public"]["Tables"]["transactions"]["Row"]>
      }
      reviews: {
        Row: {
          id: string
          agent_id: string
          user_id: string
          rating: number
          title: string | null
          body: string | null
          status: "pending" | "approved" | "rejected"
          helpful_count: number
          created_at: string
          updated_at: string
        }
        Insert: Partial<Database["public"]["Tables"]["reviews"]["Row"]> & { agent_id: string; user_id: string; rating: number }
        Update: Partial<Database["public"]["Tables"]["reviews"]["Row"]>
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          title: string
          body: string
          type: string
          is_read: boolean
          action_url: string | null
          metadata: Json
          created_at: string
        }
        Insert: Partial<Database["public"]["Tables"]["notifications"]["Row"]> & { user_id: string; title: string; body: string; type: string }
        Update: Partial<Database["public"]["Tables"]["notifications"]["Row"]>
      }
      collections: {
        Row: {
          id: string
          user_id: string
          name: string
          description: string | null
          is_public: boolean
          agent_ids: string[]
          created_at: string
        }
        Insert: Partial<Database["public"]["Tables"]["collections"]["Row"]> & { user_id: string; name: string }
        Update: Partial<Database["public"]["Tables"]["collections"]["Row"]>
      }
      agent_analytics: {
        Row: {
          id: string
          agent_id: string
          date: string
          executions: number
          successful: number
          failed: number
          unique_users: number
          revenue: number
          avg_latency_ms: number
        }
        Insert: Partial<Database["public"]["Tables"]["agent_analytics"]["Row"]> & { agent_id: string; date: string }
        Update: Partial<Database["public"]["Tables"]["agent_analytics"]["Row"]>
      }
      payouts: {
        Row: {
          id: string
          seller_id: string
          stripe_payout_id: string | null
          amount: number
          currency: string
          status: "pending" | "processing" | "paid" | "failed"
          period_start: string | null
          period_end: string | null
          created_at: string
          paid_at: string | null
        }
        Insert: Partial<Database["public"]["Tables"]["payouts"]["Row"]> & { seller_id: string; amount: number }
        Update: Partial<Database["public"]["Tables"]["payouts"]["Row"]>
      }
    }
    Views: {}
    Functions: {}
    Enums: {
      user_role: "user" | "seller" | "admin"
      agent_status: "draft" | "pending_review" | "active" | "suspended" | "archived"
      pricing_model: "free" | "per_call" | "subscription" | "freemium"
      execution_status: "queued" | "running" | "success" | "failed" | "timeout"
      subscription_plan: "free" | "starter" | "pro" | "enterprise"
    }
  }
}
